# Generated by Django 5.1.4 on 2026-06-11 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=300)),
                ('categoria', models.CharField(blank=True, max_length=200, null=True)),
                ('contenido', models.TextField()),
                ('creado_el', models.DateTimeField(auto_now_add=True)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Plantilla de Mensaje',
                'verbose_name_plural': 'Plantillas de Mensajes',
                'ordering': ['categoria', 'titulo'],
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('codigo', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('producto', models.TextField()),
                ('tipo', models.CharField(blank=True, max_length=200, null=True)),
                ('precio_usd', models.FloatField(default=0)),
                ('precio_bcv', models.FloatField(default=0)),
                ('actualizado_el', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Producto',
                'verbose_name_plural': 'Productos',
                'ordering': ['codigo'],
            },
        ),
    ]
