# Generated by Django 6.0.6 on 2026-06-11 23:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reply', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='messagetemplate',
            name='copy_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
