# Generated by Django 6.0.5 on 2026-05-21 17:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('last_four', models.CharField(max_length=4)),
                ('cutoff_day', models.PositiveIntegerField(blank=True, null=True)),
                ('payment_day', models.PositiveIntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeRateLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('bcv_rate', models.DecimalField(decimal_places=4, max_digits=12)),
                ('binance_rate', models.DecimalField(blank=True, decimal_places=4, max_digits=12, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('TDC', 'Tarjeta de Crédito'), ('DEBIT', 'Débito')], max_length=10)),
                ('booking_date', models.DateTimeField()),
                ('description', models.CharField(max_length=255)),
                ('amount_ves', models.DecimalField(decimal_places=2, max_digits=15)),
                ('reference', models.CharField(blank=True, max_length=50, null=True)),
                ('status', models.CharField(choices=[('PENDIENTE', 'Pendiente por Cortar'), ('CORTADO_NO_PAGADO', 'Cortado No Pagado'), ('PAGADO', 'Pagado')], default='PENDIENTE', max_length=20)),
                ('card', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banesco_tracker.creditcard')),
                ('exchange_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='transactions', to='banesco_tracker.exchangeratelog')),
            ],
            options={
                'ordering': ['-booking_date'],
                'constraints': [models.UniqueConstraint(fields=('card', 'booking_date', 'amount_ves', 'reference'), name='unique_banesco_transaction')],
            },
        ),
    ]
