# Generated by Django 6.0.5 on 2026-05-21 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banesco_tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='annual_interest_rate',
            field=models.DecimalField(decimal_places=2, default=40.0, max_digits=5),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='card_type_display',
            field=models.CharField(default='VISA DORADA', max_length=50),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='theme_color',
            field=models.CharField(choices=[('gold', 'Dorado Metálico'), ('platinum', 'Gris Platino Oscuro'), ('green', 'Verde Esmeralda'), ('blue', 'Azul Zafiro'), ('purple', 'Violeta Real'), ('black', 'Carbono Profundo'), ('silver', 'Plata Metálica'), ('white', 'Hielo Blanco'), ('red', 'Rubí Intenso')], default='gold', max_length=20),
        ),
    ]
