# Generated by Django 6.0.5 on 2026-05-21 22:18

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banesco_tracker', '0002_creditcard_annual_interest_rate_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='available_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='credit_limit',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='interest_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('60.00'), max_digits=5),
        ),
        migrations.AddField(
            model_name='creditcard',
            name='mora_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('3.00'), max_digits=5),
        ),
    ]
