# Generated by Django 6.0.5 on 2026-05-21 22:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banesco_tracker', '0003_creditcard_available_limit_creditcard_credit_limit_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='available_limit',
        ),
    ]
