# Generated by Django 6.0.5 on 2026-05-21 23:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('banesco_tracker', '0004_remove_creditcard_available_limit'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='creditcard',
            name='annual_interest_rate',
        ),
    ]
