# Generated by Django 6.0.5 on 2026-05-22 12:52

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banesco_tracker', '0005_remove_creditcard_annual_interest_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='BankAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Cuenta Corriente Banesco', max_length=50)),
                ('account_number', models.CharField(max_length=20, unique=True)),
                ('last_four', models.CharField(max_length=4)),
                ('initial_balance', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15)),
            ],
        ),
        migrations.AddField(
            model_name='creditcard',
            name='associated_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cards', to='banesco_tracker.bankaccount'),
        ),
        migrations.CreateModel(
            name='BankAccountTransaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateTimeField()),
                ('reference', models.CharField(max_length=50, unique=True)),
                ('description', models.CharField(max_length=255)),
                ('amount_ves', models.DecimalField(decimal_places=2, max_digits=15)),
                ('balance_ves', models.DecimalField(blank=True, decimal_places=2, max_digits=15, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='transactions', to='banesco_tracker.bankaccount')),
                ('exchange_rate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_transactions', to='banesco_tracker.exchangeratelog')),
                ('reconciled_transaction', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bank_relation', to='banesco_tracker.transaction')),
            ],
            options={
                'ordering': ['-booking_date'],
            },
        ),
    ]
