# Generated by Django 6.0.5 on 2026-05-22 13:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banesco_tracker', '0006_bankaccount_creditcard_associated_account_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bankaccounttransaction',
            name='reconciled_transaction',
        ),
        migrations.AddField(
            model_name='transaction',
            name='bank_relation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reconciled_transactions', to='banesco_tracker.bankaccounttransaction'),
        ),
    ]
