# Generated by Django 6.0.5 on 2026-05-22 13:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banesco_tracker', '0007_remove_bankaccounttransaction_reconciled_transaction_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='bank_relation',
        ),
        migrations.CreateModel(
            name='TransactionReconciliation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reconciled_amount', models.DecimalField(decimal_places=2, max_digits=15)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('bank_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='banesco_tracker.bankaccounttransaction')),
                ('card_transaction', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconciliations', to='banesco_tracker.transaction')),
            ],
            options={
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('bank_transaction', 'card_transaction'), name='unique_reconciliation_pair')],
            },
        ),
    ]
