# Generated by Django 6.0.5 on 2026-05-22 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banesco_tracker', '0008_remove_transaction_bank_relation_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccounttransaction',
            name='is_manual',
            field=models.BooleanField(default=False),
        ),
    ]
