# Generated by Django 6.0.5 on 2026-05-23 00:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banesco_tracker', '0009_bankaccounttransaction_is_manual'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankaccount',
            name='account_type',
            field=models.CharField(choices=[('current', 'Cuenta Corriente'), ('savings', 'Cuenta de Ahorros')], default='current', max_length=20),
        ),
    ]
