# Generated by Django 6.0.5 on 2026-06-09 03:47

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banesco_tracker', '0010_bankaccount_account_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='previous_balance',
            field=models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=15),
        ),
    ]
