# Generated by Django 6.0.5 on 2026-06-09 20:05

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('banesco_tracker', '0011_add_previous_balance'),
    ]

    operations = [
        migrations.AddField(
            model_name='creditcard',
            name='minimum_payment_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.20'), max_digits=5),
        ),
    ]
